version: 2.1

commands:
  yarn_hello:
    steps:
      - run: |
          yarn hello

executors:
  node:
    docker:
      - image: circleci/node:14.17.0

workflows:
  hello:
    jobs:
      perform_hello:
        executor: node
        steps:
          - checkout
          - yarn_hello
